name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, rpi]  # Specify the label for the self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Raspberry Pi
      run: |
        set -e
        cd /home/pi/rpirepo
        git fetch origin main
        git reset --hard origin/main
        source venv/bin/activate
        sudo systemctl restart flaskapp
