name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - dev  # or whichever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          cd /home/rpi/rpirepo
          git pull origin main
          source venv/bin/activate
          sudo systemctl restart flaskapp
